source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'MRGArchitect_Example' do
  pod 'MRGArchitect', :path => '../'

  target 'MRGArchitect_Tests' do
    inherit! :search_paths
    pod 'OCMock', '~> 3.4'
  end
end
